install: gradle wrapper --gradle-version 4.4

language: java

jdk:
  - oraclejdk9

script: gradle clean build

notifications:
  email:
    recipients:
      - fishercoder@gmail.com
    on_failure: always

